// Code generated by workflowgen; DO NOT EDIT.
package main

import (
	"context"
	"time"

	"github.com/flandersrin/workflow-go/workflow"
)

const WorkflowName = "order"
const WorkflowVersion = "v1"

const (
	StatePending workflow.StateName = "PENDING"
	StatePaid    workflow.StateName = "PAID"
	StateFailed  workflow.StateName = "FAILED"
)

const (
	EventPaymentOk     workflow.EventName = "PAYMENT_OK"
	EventPaymentFailed workflow.EventName = "PAYMENT_FAILED"
)

const (
	TaskChargePayment workflow.TaskName = "charge_payment"
)

const (
	HandlerPaymentCharge workflow.HandlerName = "payment.charge"
)

func Definition() *workflow.WorkflowDefinition {
	return workflow.NewDefinition(WorkflowName, WorkflowVersion).
		Initial(StatePending).
		State(StatePending, workflow.OnEnter(TaskChargePayment)).
		State(StatePaid, workflow.Terminal()).
		State(StateFailed, workflow.Terminal()).
		Event(EventPaymentOk).
		Event(EventPaymentFailed).
		Task(TaskChargePayment, HandlerPaymentCharge, workflow.Retry(3, mustDuration("1s")), workflow.OnSuccess(EventPaymentOk), workflow.OnFailure(EventPaymentFailed)).
		Transition("payment_ok", StatePending, EventPaymentOk, StatePaid).
		Transition("payment_failed", StatePending, EventPaymentFailed, StateFailed).
		Build()
}

func Machine() *workflow.Machine {
	machine, err := workflow.Compile(Definition())
	if err != nil {
		panic(err)
	}
	return machine
}

func Register(runtime *workflow.Runtime) {
	runtime.RegisterMachine(Machine())
}

func RegisterTask(runtime *workflow.Runtime, handler workflow.HandlerName, task workflow.TaskHandler) {
	runtime.RegisterTask(string(handler), task)
}

func StartOptions(instanceID string, data map[string]any) workflow.StartOptions {
	return workflow.StartOptions{
		InstanceID: instanceID,
		Workflow:   WorkflowName,
		Version:    WorkflowVersion,
		Data:       data,
	}
}

func Start(ctx context.Context, runtime *workflow.Runtime, instanceID string, data map[string]any) (*workflow.WorkflowInstance, error) {
	return runtime.StartWorkflow(ctx, StartOptions(instanceID, data))
}

func SignalOptions(instanceID string, event workflow.EventName, payload map[string]any) workflow.SignalOptions {
	return workflow.SignalOptions{
		InstanceID: instanceID,
		Event:      string(event),
		Payload:    payload,
	}
}

func Signal(ctx context.Context, runtime *workflow.Runtime, instanceID string, event workflow.EventName, payload map[string]any) (*workflow.WorkflowInstance, error) {
	return runtime.SignalWorkflow(ctx, SignalOptions(instanceID, event, payload))
}

func mustDuration(value string) time.Duration {
	duration, err := time.ParseDuration(value)
	if err != nil {
		panic(err)
	}
	return duration
}
