package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

type spec struct {
	Package     string      `yaml:"package"`
	Workflow    string      `yaml:"workflow"`
	Version     string      `yaml:"version"`
	Initial     string      `yaml:"initial"`
	States      []stateSpec `yaml:"states"`
	Events      []namedSpec `yaml:"events"`
	Tasks       []taskSpec  `yaml:"tasks"`
	Transitions []transSpec `yaml:"transitions"`
}

type stateSpec struct {
	Name     string   `yaml:"name"`
	Terminal bool     `yaml:"terminal"`
	OnEnter  []string `yaml:"on_enter"`
}

type namedSpec struct {
	Name string `yaml:"name"`
}

type taskSpec struct {
	Name         string `yaml:"name"`
	Handler      string `yaml:"handler"`
	MaxAttempts  int    `yaml:"max_attempts"`
	Backoff      string `yaml:"backoff"`
	Timeout      string `yaml:"timeout"`
	Compensation string `yaml:"compensation"`
	OnSuccess    string `yaml:"on_success"`
	OnFailure    string `yaml:"on_failure"`
}

type transSpec struct {
	Name  string `yaml:"name"`
	From  string `yaml:"from"`
	Event string `yaml:"event"`
	To    string `yaml:"to"`
}

func main() {
	in := flag.String("in", "", "输入 workflow.yaml")
	out := flag.String("out", "", "输出 Go 文件")
	flag.Parse()
	if *in == "" || *out == "" {
		panic("usage: workflowgen --in workflow.yaml --out workflow_gen.go")
	}
	raw, err := os.ReadFile(*in)
	if err != nil {
		panic(err)
	}
	var s spec
	if err := yaml.Unmarshal(raw, &s); err != nil {
		panic(err)
	}
	if s.Package == "" {
		s.Package = "workflowdef"
	}
	rendered, err := render(s)
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile(*out, rendered, 0o644); err != nil {
		panic(err)
	}
}

func render(s spec) ([]byte, error) {
	data := struct {
		Spec       spec
		WorkflowID string
		States     []constant
		Events     []constant
		Tasks      []constant
		Handlers   []constant
	}{
		Spec:       s,
		WorkflowID: exported(s.Workflow),
		States:     constants("State", namesFromStates(s.States)),
		Events:     constants("Event", namesFromNamed(s.Events)),
		Tasks:      constants("Task", namesFromTasks(s.Tasks)),
		Handlers:   constants("Handler", handlersFromTasks(s.Tasks)),
	}
	var buf bytes.Buffer
	if err := fileTemplate.Execute(&buf, data); err != nil {
		return nil, err
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("%w\n%s", err, buf.String())
	}
	return formatted, nil
}

type constant struct {
	GoName string
	Value  string
}

func constants(prefix string, values []string) []constant {
	out := make([]constant, 0, len(values))
	seen := map[string]bool{}
	for _, value := range values {
		if value == "" || seen[value] {
			continue
		}
		seen[value] = true
		out = append(out, constant{GoName: prefix + exported(value), Value: value})
	}
	return out
}

func namesFromStates(items []stateSpec) []string {
	out := make([]string, 0, len(items))
	for _, item := range items {
		out = append(out, item.Name)
	}
	return out
}

func namesFromNamed(items []namedSpec) []string {
	out := make([]string, 0, len(items))
	for _, item := range items {
		out = append(out, item.Name)
	}
	return out
}

func namesFromTasks(items []taskSpec) []string {
	out := make([]string, 0, len(items))
	for _, item := range items {
		out = append(out, item.Name)
	}
	return out
}

func handlersFromTasks(items []taskSpec) []string {
	out := make([]string, 0, len(items))
	for _, item := range items {
		out = append(out, item.Handler)
	}
	return out
}

func exported(value string) string {
	parts := strings.FieldsFunc(value, func(r rune) bool {
		return r == '_' || r == '-' || r == '.' || r == ' '
	})
	var b strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		part = strings.ToLower(part)
		b.WriteString(strings.ToUpper(part[:1]))
		if len(part) > 1 {
			b.WriteString(part[1:])
		}
	}
	return b.String()
}

var fileTemplate = template.Must(template.New("file").Funcs(template.FuncMap{
	"state":   func(v string) string { return "State" + exported(v) },
	"event":   func(v string) string { return "Event" + exported(v) },
	"task":    func(v string) string { return "Task" + exported(v) },
	"handler": func(v string) string { return "Handler" + exported(v) },
}).Parse(`// Code generated by workflowgen; DO NOT EDIT.
package {{ .Spec.Package }}

import (
	"context"
	"time"

	"github.com/flandersrin/workflow-go/workflow"
)

const WorkflowName = "{{ .Spec.Workflow }}"
const WorkflowVersion = "{{ .Spec.Version }}"

const (
{{- range .States }}
	{{ .GoName }} workflow.StateName = "{{ .Value }}"
{{- end }}
)

const (
{{- range .Events }}
	{{ .GoName }} workflow.EventName = "{{ .Value }}"
{{- end }}
)

const (
{{- range .Tasks }}
	{{ .GoName }} workflow.TaskName = "{{ .Value }}"
{{- end }}
)

const (
{{- range .Handlers }}
	{{ .GoName }} workflow.HandlerName = "{{ .Value }}"
{{- end }}
)

func Definition() *workflow.WorkflowDefinition {
	return workflow.NewDefinition(WorkflowName, WorkflowVersion).
		Initial({{ state .Spec.Initial }}).
{{- range .Spec.States }}
		State({{ state .Name }}{{ if or .Terminal .OnEnter }}, {{ end }}{{ if .Terminal }}workflow.Terminal(){{ if .OnEnter }}, {{ end }}{{ end }}{{ if .OnEnter }}workflow.OnEnter({{ range $i, $task := .OnEnter }}{{ if $i }}, {{ end }}{{ task $task }}{{ end }}){{ end }}).
{{- end }}
{{- range .Spec.Events }}
		Event({{ event .Name }}).
{{- end }}
{{- range .Spec.Tasks }}
		Task({{ task .Name }}, {{ handler .Handler }}{{ if or .MaxAttempts .Backoff .Timeout .Compensation .OnSuccess .OnFailure }}, {{ end }}{{ if .MaxAttempts }}workflow.Retry({{ .MaxAttempts }}, {{ if .Backoff }}mustDuration("{{ .Backoff }}"){{ else }}time.Second{{ end }}){{ end }}{{ if .Timeout }}{{ if .MaxAttempts }}, {{ end }}workflow.Timeout(mustDuration("{{ .Timeout }}")){{ end }}{{ if .Compensation }}{{ if or .MaxAttempts .Timeout }}, {{ end }}workflow.Compensation({{ task .Compensation }}){{ end }}{{ if .OnSuccess }}{{ if or .MaxAttempts .Timeout .Compensation }}, {{ end }}workflow.OnSuccess({{ event .OnSuccess }}){{ end }}{{ if .OnFailure }}{{ if or .MaxAttempts .Timeout .Compensation .OnSuccess }}, {{ end }}workflow.OnFailure({{ event .OnFailure }}){{ end }}).
{{- end }}
{{- range .Spec.Transitions }}
		Transition("{{ .Name }}", {{ state .From }}, {{ event .Event }}, {{ state .To }}).
{{- end }}
		Build()
}

func Machine() *workflow.Machine {
	machine, err := workflow.Compile(Definition())
	if err != nil {
		panic(err)
	}
	return machine
}

func Register(runtime *workflow.Runtime) {
	runtime.RegisterMachine(Machine())
}

func RegisterTask(runtime *workflow.Runtime, handler workflow.HandlerName, task workflow.TaskHandler) {
	runtime.RegisterTask(string(handler), task)
}

func StartOptions(instanceID string, data map[string]any) workflow.StartOptions {
	return workflow.StartOptions{
		InstanceID: instanceID,
		Workflow:   WorkflowName,
		Version:    WorkflowVersion,
		Data:       data,
	}
}

func Start(ctx context.Context, runtime *workflow.Runtime, instanceID string, data map[string]any) (*workflow.WorkflowInstance, error) {
	return runtime.StartWorkflow(ctx, StartOptions(instanceID, data))
}

func SignalOptions(instanceID string, event workflow.EventName, payload map[string]any) workflow.SignalOptions {
	return workflow.SignalOptions{
		InstanceID: instanceID,
		Event:      string(event),
		Payload:    payload,
	}
}

func Signal(ctx context.Context, runtime *workflow.Runtime, instanceID string, event workflow.EventName, payload map[string]any) (*workflow.WorkflowInstance, error) {
	return runtime.SignalWorkflow(ctx, SignalOptions(instanceID, event, payload))
}

func mustDuration(value string) time.Duration {
	duration, err := time.ParseDuration(value)
	if err != nil {
		panic(err)
	}
	return duration
}
`))
